/**
 * 
 */
package com.synectiks.commons.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;

/**
 * Class to hold and translate Search Response into application class.
 * @author Rajesh
 */
@DynamoDBTable(tableName = IDBConsts.Tbl_EvalResult)
public class EvalPolicyRuleResult extends Entity {

	private static final long serialVersionUID = 2688808817348369442L;

	private String policyId;
	private String ruleId;
	private String docId;

	private boolean pass;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	@Override
	public String getName() {
		return docId;
	}

	public String getPolicyId() {
		return policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	public String getRuleId() {
		return ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	public String getDocId() {
		return docId;
	}

	public void setDocId(String docId) {
		this.docId = docId;
	}

	public boolean isPass() {
		return pass;
	}

	public void setPass(boolean pass) {
		this.pass = pass;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("{ ");
		if (id != null) {
			builder.append("\"id\": \"");
			builder.append(id);
			builder.append("\", ");
		}
		if (policyId != null) {
			builder.append("\"policyId\": \"");
			builder.append(policyId);
			builder.append("\", ");
		}
		if (ruleId != null) {
			builder.append("\"ruleId\": \"");
			builder.append(ruleId);
			builder.append("\", ");
		}
		if (docId != null) {
			builder.append("\"docId\": \"");
			builder.append(docId);
			builder.append("\", ");
		}
		builder.append("\"pass\": ");
		builder.append(pass);
		builder.append(" }");
		return builder.toString();
	}
}
