/**
 * 
 */
package com.synectiks.commons.entities;

import java.util.List;

import org.codehaus.jettison.json.JSONArray;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;

/**
 * Class to hold and translate Search Response into application class.
 * @author Rajesh
 */
@DynamoDBTable(tableName = IDBConsts.Tbl_Result)
public class PolicyRuleResult extends Entity {

	private static final long serialVersionUID = 2016053745431745972L;

	private String scrollId;
	private long totalHits;
	private long tookInMillis;
	private String policyId;
	private String ruleId;
	private List<String> hits;
	private boolean timeOut;
	private boolean terminatedEarly;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	@Override
	public String getName() {
		return scrollId;
	}

	public String getPolicyId() {
		return policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	public String getRuleId() {
		return ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	public String getScrollId() {
		return scrollId;
	}

	public void setScrollId(String scrollId) {
		this.scrollId = scrollId;
	}

	public long getTotalHits() {
		return totalHits;
	}

	public void setTotalHits(long totalHits) {
		this.totalHits = totalHits;
	}

	public long getTookInMillis() {
		return tookInMillis;
	}

	public void setTookInMillis(long tookInMillis) {
		this.tookInMillis = tookInMillis;
	}

	public List<String> getHits() {
		return hits;
	}

	public void setHits(List<String> hits) {
		this.hits = hits;
	}

	public boolean isTimeOut() {
		return timeOut;
	}

	public void setTimeOut(boolean timeOut) {
		this.timeOut = timeOut;
	}

	public boolean isTerminatedEarly() {
		return terminatedEarly;
	}

	public void setTerminatedEarly(boolean terminatedEarly) {
		this.terminatedEarly = terminatedEarly;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("{ ");
		if (id != null) {
			builder.append("\"id\": \"");
			builder.append(id);
			builder.append("\", ");
		}
		if (scrollId != null) {
			builder.append("\"scrollId\": \"");
			builder.append(scrollId);
			builder.append("\", ");
		}
		builder.append("\"totalHits\": ");
		builder.append(totalHits);
		builder.append(", \"tookInMillis\": ");
		builder.append(tookInMillis);
		builder.append(", ");
		if (hits != null) {
			builder.append("\"hits\": ");
			builder.append(new JSONArray(hits).toString());
			builder.append(", ");
		}
		if (policyId != null) {
			builder.append("\"policyId\": \"");
			builder.append(policyId);
			builder.append("\", ");
		}
		if (ruleId != null) {
			builder.append("\"ruleId\": \"");
			builder.append(ruleId);
			builder.append("\", ");
		}
		builder.append("\"timeOut\": ");
		builder.append(timeOut);
		builder.append(", \"terminatedEarly\": ");
		builder.append(terminatedEarly);
		builder.append(" }");
		return builder.toString();
	}
}
