/**
 * 
 */
package com.synectiks.commons.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;

/**
 * Sample Policy:
 * 
 * <pre>
 * {
 *	'PasswordPolicy': {
 *		'MinimumPasswordLength': 123,
 *		'RequireSymbols': True|False,
 *		'RequireNumbers': True|False,
 *		'RequireUppercaseCharacters': True|False,
 *		'RequireLowercaseCharacters': True|False,
 *		'AllowUsersToChangePassword': True|False,
 *		'ExpirePasswords': True|False,
 *		'MaxPasswordAge': 123,
 *		'PasswordReusePrevention': 123,
 *		'HardExpiry': True|False
 *	}
 * }
 * </pre>
 * @author Rajesh
 */
@DynamoDBTable(tableName = IDBConsts.Tbl_Policy)
public class Policy extends Entity {

	private static final long serialVersionUID = -6631676861385312561L;

	private String name;
	private String json;
	private String cmdType;
	private String command;

	private String description;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJson() {
		return json;
	}

	public void setJson(String json) {
		this.json = json;
	}

	public String getCmdType() {
		return cmdType;
	}

	public void setCmdType(String cmdType) {
		this.cmdType = cmdType;
	}

	public String getCommand() {
		return command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public String toString() {
		return "{ " + (name != null ? "\"name\": \"" + name + "\", " : "")
				+ (description != null ? "\"description\": \"" + description + "\", " : "")
				+ (json != null ? "\"json\": \"" + json + "\", " : "")
				+ (cmdType != null ? "\"cmdType\": \"" + cmdType + "\", " : "")
				+ (command != null ? "\"event\": \"" + command + "\"" : "") + "}";
	}

}
