/**
 * 
 */
package com.synectiks.commons.entities;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;

/**
 * Sample Policy:
 * <pre> * {
 *	"name": "policy-name",
 *	"description": "",
 *	"rules": [
 *		{
 *			"name": "rule-name",
 *			"entity": "entity-name",
 *			"description": "",
 *			"checks: [
 *				"key > 10",
 *				"key regex('^R.*esh$')",
 *				"key isNotEmpty",
 *				"key >= toDate('2018-08-15 13:20:30', 'yyyy-MM-dd HH:mm:ss')",
 *				"(root.node.key1 = value1 OR key2 = value2)",
 *				"(root.node.key1 = value1 OR key2 = value2) AND (root.node.key3 = value3)"
 *			]
 *		}
 *	]
 * }
 * </pre>
 * @author Rajesh
 */
@DynamoDBTable(tableName = IDBConsts.Tbl_Policy)
public class Policy extends Entity {

	private static final long serialVersionUID = -6631676861385312561L;

	private String name;
	private List<String> rules;
	private String description;

	public Policy() {
	}

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<String> getRules() {
		return rules;
	}

	public void setRules(List<String> rules) {
		this.rules = rules;
	}

	@Override
	public String toString() {
		return "{ " + (id != null ? "\"id\": \"" + id + "\", " : "")
				+ (name != null ? "\"name\": \"" + name + "\", " : "")
				+ (description != null ? "\"description\": \"" + description + "\", " : "")
				+ (rules != null ? "\"rules\": \"" + rules + "\"" : "") + "}";
	}

}
