/**
 * 
 */
package com.synectiks.commons.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;
import com.synectiks.commons.utils.IUtils;

/**
 * @author Rajesh Upadhyay
 */
@DynamoDBTable(tableName = IDBConsts.Tbl_SSM)
public class SSMachine extends Entity {

	private static final long serialVersionUID = -6456129989903870872L;

	private String name;
	private String ssmId;
	private String ssmContext;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "indx_SM_ID")
	public String getSsmId() {
		return ssmId;
	}

	@Override
	public String getName() {
		if (IUtils.isNullOrEmpty(name) && !IUtils.isNullOrEmpty(ssmId)) {
			if (ssmId.indexOf(":") != -1) {
				name = ssmId.substring(0, ssmId.indexOf(":"));
			}
		}
		return name;
	}

	public String getSsmContext() {
		return ssmContext;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setSsmContext(String ssmContext) {
		this.ssmContext = ssmContext;
	}

	public void setSsmId(String ssmId) {
		this.ssmId = ssmId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("{");
		if (ssmId != null) {
			builder.append("\"ssmId\": \"");
			builder.append(ssmId);
			builder.append("\"");
		}
		if (ssmContext != null) {
			builder.append(builder.length() > 1 ? ", " : "");
			builder.append("\"ssmContext\": \"");
			builder.append(ssmContext);
			builder.append("\"");
		}
		if (name != null) {
			builder.append(builder.length() > 1 ? ", " : "");
			builder.append("\"name\": \"");
			builder.append(name + "\"");
		}
		if (id != null) {
			builder.append(builder.length() > 1 ? ", " : "");
			builder.append("\"id\": \"");
			builder.append(id + "\"");
		}
		builder.append(" }");
		return builder.toString();
	}

}
