/**
 * 
 */
package com.synectiks.commons.entities.dynamodb;

import org.springframework.data.elasticsearch.annotations.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.synectiks.commons.constants.IConsts;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.converters.CategoryConverter;
import com.synectiks.commons.interfaces.IESEntity;

/**
 * @author Rajesh
 */
@DynamoDBTable(tableName = IDBConsts.Tbl_SERVICE)
@Document(indexName = IConsts.INDX_SERVICE, type = IConsts.INDX_TYPE_SERVICE)
public class Service extends Entity implements IESEntity {

	private static final long serialVersionUID = 4824340265742008347L;

	private String name;
	private Category category;
	private String description;
	private String SLA;

	public Service() {
		super();
	}

	public Service(String name) {
		this();
		this.name = name;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBTypeConverted(converter = CategoryConverter.class)
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSLA() {
		return SLA;
	}

	public void setSLA(String sLA) {
		SLA = sLA;
	}

	@Override
	public String toString() {
		return String.format(
				"{\"name\": \"%s\", \"category\": %s, \"description\": \"%s\","
				+ " \"SLA\": \"%s\", \"id\": \"%s\", \"createdAt\": \"%s\", "
				+ "\"updatedAt\": \"%s\", \"createdBy\": \"%s\", \"updatedBy\": \"%s\"}",
				name, category, description, SLA, id, createdAt, updatedAt, createdBy,
				updatedBy);
	}
}
