package com.synectiks.commons.entities.demo;

import org.springframework.data.elasticsearch.annotations.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;
import com.synectiks.commons.interfaces.IESEntity;

/**
 * @author Rajesh
 */
@DynamoDBTable(tableName = CartItem.Tbl_CART_ITEM)
@Document(indexName = CartItem.INDX_CART_ITEM, type = CartItem.INDX_TYPE_CART_ITEM)
public class CartItem extends Entity implements IESEntity {

	private static final long serialVersionUID = -5425701670023632251L;

	public static final String Tbl_CART_ITEM = "cartItem";
	public static final String INDX_CART_ITEM = "indx_cartItem";
	public static final String INDX_TYPE_CART_ITEM = "indx_type_cartItem";

	private int quantity;
	private String productId;
	private String state;
	private double totalPrice;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "indx_Cart_ProductId")
	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public double getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}
}
