package com.synectiks.commons.entities.demo;

import org.springframework.data.elasticsearch.annotations.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;
import com.synectiks.commons.interfaces.IESEntity;

/**
 * @author Rajesh
 */
@DynamoDBTable(tableName = CustomerOrder.Tbl_ORDER)
@Document(indexName = CustomerOrder.INDX_ORDER, type = CustomerOrder.INDX_TYPE_ORDER)
public class CustomerOrder extends Entity implements IESEntity {

	private static final long serialVersionUID = 6902795012956582819L;

	public static final String Tbl_ORDER = "order";
	public static final String INDX_ORDER = "indx_order";
	public static final String INDX_TYPE_ORDER = "indx_type_order";

	private String cartId;
	private String customerId;
	private String billingId;
	private String shippingId;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	@Override
	public String getName() {
		return cartId;
	}

	public String getCartId() {
		return cartId;
	}

	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getBillingId() {
		return billingId;
	}

	public void setBillingId(String billingId) {
		this.billingId = billingId;
	}

	public String getShippingId() {
		return shippingId;
	}

	public void setShippingId(String shippingId) {
		this.shippingId = shippingId;
	}
}
