package com.synectiks.commons.entities.demo;

import org.springframework.data.elasticsearch.annotations.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.synectiks.commons.constants.IDBConsts;
import com.synectiks.commons.entities.dynamodb.Entity;
import com.synectiks.commons.interfaces.IESEntity;

/**
 * @author Rajesh
 */
@DynamoDBTable(tableName = Customer.Tbl_CUSTOMER)
@Document(indexName = Customer.INDX_CUSTOMER, type = Customer.INDX_TYPE_CUSTOMER)
public class Customer extends Entity implements IESEntity {

    private static final long serialVersionUID = -2039869419395635053L;

	public static final String Tbl_CUSTOMER = "customer";
	public static final String INDX_CUSTOMER = "indx_customer";
	public static final String INDX_TYPE_CUSTOMER = "indx_type_customer";

    private String cartId;
    private String name;
    private String email;
    private String phone;
    private String username;
    private String password;
    private boolean enabled;
    private String billingId;
    private String shippingId;

	@Override
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = IDBConsts.Col_ID)
	public String getId() {
		return id;
	}

	public String getCartId() {
		return cartId;
	}

	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "indx_Cust_Email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "indx_Cust_UserName")
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getBillingId() {
		return billingId;
	}

	public void setBillingId(String billingId) {
		this.billingId = billingId;
	}

	public String getShippingId() {
		return shippingId;
	}

	public void setShippingId(String shippingId) {
		this.shippingId = shippingId;
	}
}
